#!/usr/bin/env php
<?php

unset($REX);
$REX['REDAXO'] = true;
$REX['HTDOCS_PATH'] = '../';
$REX['BACKEND_FOLDER'] = 'redaxo';

require __DIR__.'/../src/path_provider.php';
$REX['PATH_PROVIDER'] = new app_path_provider();

chdir(dirname(__DIR__));

require $REX['PATH_PROVIDER']->core('console.php');
