; SHA ermitteln
; $ curl -Ls https://github.com/redaxo/redaxo/releases/download/5.21.4/redaxo_5.21.4.zip | shasum

REDAXO_VERSION="5.21.4"
REDAXO_SHA="22b3c03b58564acc96aca22d2687597d571fd527"

[https://api.github.com/repos/FriendsOfREDAXO/]
ADDONS[]=adminer
ADDONS[]=developer
ADDONS[]=focuspoint
ADDONS[]=mblock
ADDONS[]=quick_navigation

[https://api.github.com/repos/tbaddade/]
ADDONS[sprog]=redaxo_sprog
ADDONS[url]=redaxo_url
ADDONS[watson]=redaxo_watson

[https://api.github.com/repos/yakamara/]
ADDONS[]=ydeploy
ADDONS[]=yform
ADDONS[]=yrewrite
