; SHA ermitteln
; $ curl -Ls https://github.com/redaxo/redaxo/releases/download/5.20.0/redaxo_5.20.0.zip | shasum

REDAXO_VERSION="5.20.0"
REDAXO_SHA="eda0101aa2035c19ec721f55ffa23e7e61335cba"

[https://api.github.com/repos/FriendsOfREDAXO/]
ADDONS[]=adminer
ADDONS[]=developer
ADDONS[]=focuspoint
ADDONS[]=mblock
ADDONS[]=quick_navigation

[https://api.github.com/repos/tbaddade/]
ADDONS[sprog]=redaxo_sprog
ADDONS[url]=redaxo_url
ADDONS[watson]=redaxo_watson

[https://api.github.com/repos/yakamara/]
ADDONS[]=ydeploy
ADDONS[]=yform
ADDONS[]=yrewrite
